-- ===== SEED Feuilles de marche SOTRACO Bobo (période scolaire) =====
-- Remplace l'ancien B11 (nouvelle feuille complète)
delete from departs where ligne = 'B11';

insert into departs (ligne, ville, terminus, jours, heure) values
-- ===== B1 : Cité U Belle-Ville ↔ Tiéfo Amoro =====
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','05:30'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','07:05'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','08:25'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','10:20'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','12:05'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','13:30'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','14:50'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','16:10'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','17:30'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','18:50'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','sem','20:15'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','dim','07:00'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','dim','09:00'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','dim','11:00'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','dim','13:00'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','dim','15:00'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','dim','17:00'),
('B1','Bobo-Dioulasso','Cité U Belle-Ville','dim','19:00'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','dim','14:00'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','dim','16:00'),
('B1','Bobo-Dioulasso','Tiéfo Amoro','dim','18:00'),
-- ===== B1B : Belle-Ville via INSSA ↔ Tiéfo Amoro =====
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','05:45'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','06:30'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','07:05'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','07:45'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','08:25'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','09:05'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','10:20'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','11:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','12:05'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','12:45'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','13:30'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','14:10'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','14:50'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','15:30'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','16:10'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','16:50'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','17:30'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','18:10'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','18:50'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','19:30'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','sem','20:15'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','05:55'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','07:05'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','08:25'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','10:20'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','12:05'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','13:30'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','14:50'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','16:10'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','17:30'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','18:50'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','sem','20:15'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','07:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','09:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','11:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','13:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','14:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','15:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','16:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','17:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','18:00'),
('B1B','Bobo-Dioulasso','Belle-Ville via INSSA','dim','19:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','07:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','09:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','11:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','13:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','15:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','17:00'),
('B1B','Bobo-Dioulasso','Tiéfo Amoro','dim','19:00'),
-- ===== B2 : Station Oryx rte Ouaga ↔ Tiéfo Amoro =====
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','05:45'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','07:05'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','08:25'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','10:20'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','12:05'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','13:30'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','14:50'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','16:10'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','17:30'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','18:50'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','sem','20:15'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','dim','07:00'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','dim','09:00'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','dim','11:00'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','dim','13:00'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','dim','15:00'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','dim','17:00'),
('B2','Bobo-Dioulasso','Station Oryx rte Ouaga','dim','19:00'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','dim','14:00'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','dim','16:00'),
('B2','Bobo-Dioulasso','Tiéfo Amoro','dim','18:00'),
-- ===== B2B : Yegueresso ↔ Tiéfo Amoro =====
('B2B','Bobo-Dioulasso','Yegueresso','sem','06:00'),
('B2B','Bobo-Dioulasso','Yegueresso','sem','08:00'),
('B2B','Bobo-Dioulasso','Yegueresso','sem','10:00'),
('B2B','Bobo-Dioulasso','Yegueresso','sem','12:00'),
('B2B','Bobo-Dioulasso','Yegueresso','sem','14:00'),
('B2B','Bobo-Dioulasso','Yegueresso','sem','16:00'),
('B2B','Bobo-Dioulasso','Yegueresso','sem','18:00'),
('B2B','Bobo-Dioulasso','Yegueresso','sem','20:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','sem','07:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','sem','09:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','sem','13:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','sem','15:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','sem','17:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','sem','19:00'),
('B2B','Bobo-Dioulasso','Yegueresso','dim','08:00'),
('B2B','Bobo-Dioulasso','Yegueresso','dim','10:00'),
('B2B','Bobo-Dioulasso','Yegueresso','dim','12:00'),
('B2B','Bobo-Dioulasso','Yegueresso','dim','14:00'),
('B2B','Bobo-Dioulasso','Yegueresso','dim','16:00'),
('B2B','Bobo-Dioulasso','Yegueresso','dim','18:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','dim','07:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','dim','09:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','dim','11:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','dim','13:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','dim','15:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','dim','17:00'),
('B2B','Bobo-Dioulasso','Tiéfo Amoro','dim','19:00'),
-- ===== B4 : Station Orix rte Ouaga ↔ Tiéfo Amoro =====
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','05:50'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','07:10'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','08:30'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','09:50'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','11:10'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','12:30'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','13:50'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','15:10'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','16:30'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','17:50'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','sem','19:10'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','06:30'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','07:50'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','09:10'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','10:30'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','11:50'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','13:10'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','14:30'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','15:50'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','17:10'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','sem','18:30'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','dim','08:00'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','dim','10:00'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','dim','12:00'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','dim','14:00'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','dim','16:00'),
('B4','Bobo-Dioulasso','Station Orix rte Ouaga','dim','18:00'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','dim','07:00'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','dim','09:00'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','dim','11:00'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','dim','13:00'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','dim','15:00'),
('B4','Bobo-Dioulasso','Tiéfo Amoro','dim','17:00'),
-- ===== B5 : Farakoba ↔ Tiéfo Amoro =====
('B5','Bobo-Dioulasso','Farakoba','sem','05:45'),
('B5','Bobo-Dioulasso','Farakoba','sem','06:25'),
('B5','Bobo-Dioulasso','Farakoba','sem','07:05'),
('B5','Bobo-Dioulasso','Farakoba','sem','07:45'),
('B5','Bobo-Dioulasso','Farakoba','sem','08:25'),
('B5','Bobo-Dioulasso','Farakoba','sem','09:05'),
('B5','Bobo-Dioulasso','Farakoba','sem','10:20'),
('B5','Bobo-Dioulasso','Farakoba','sem','11:00'),
('B5','Bobo-Dioulasso','Farakoba','sem','12:05'),
('B5','Bobo-Dioulasso','Farakoba','sem','12:45'),
('B5','Bobo-Dioulasso','Farakoba','sem','13:30'),
('B5','Bobo-Dioulasso','Farakoba','sem','14:10'),
('B5','Bobo-Dioulasso','Farakoba','sem','14:50'),
('B5','Bobo-Dioulasso','Farakoba','sem','15:30'),
('B5','Bobo-Dioulasso','Farakoba','sem','16:10'),
('B5','Bobo-Dioulasso','Farakoba','sem','16:50'),
('B5','Bobo-Dioulasso','Farakoba','sem','17:30'),
('B5','Bobo-Dioulasso','Farakoba','sem','18:10'),
('B5','Bobo-Dioulasso','Farakoba','sem','18:50'),
('B5','Bobo-Dioulasso','Farakoba','sem','19:30'),
('B5','Bobo-Dioulasso','Farakoba','sem','20:15'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','05:45'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','07:05'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','08:25'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','10:20'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','12:05'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','13:30'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','14:50'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','16:10'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','17:30'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','18:50'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','sem','20:15'),
('B5','Bobo-Dioulasso','Farakoba','dim','07:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','08:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','09:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','10:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','11:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','12:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','13:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','14:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','15:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','16:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','17:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','18:00'),
('B5','Bobo-Dioulasso','Farakoba','dim','19:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','07:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','09:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','11:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','13:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','14:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','15:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','16:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','17:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','18:00'),
('B5','Bobo-Dioulasso','Tiéfo Amoro','dim','19:00'),
-- ===== B6 : Logements sociaux ↔ Tiéfo Amoro =====
('B6','Bobo-Dioulasso','Logements sociaux','sem','05:35'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','07:05'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','08:25'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','10:20'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','12:05'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','13:30'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','14:50'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','16:10'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','17:30'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','18:50'),
('B6','Bobo-Dioulasso','Logements sociaux','sem','20:15'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B6','Bobo-Dioulasso','Logements sociaux','dim','07:00'),
('B6','Bobo-Dioulasso','Logements sociaux','dim','09:00'),
('B6','Bobo-Dioulasso','Logements sociaux','dim','11:00'),
('B6','Bobo-Dioulasso','Logements sociaux','dim','13:00'),
('B6','Bobo-Dioulasso','Logements sociaux','dim','15:00'),
('B6','Bobo-Dioulasso','Logements sociaux','dim','17:00'),
('B6','Bobo-Dioulasso','Logements sociaux','dim','19:00'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','dim','14:00'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','dim','16:00'),
('B6','Bobo-Dioulasso','Tiéfo Amoro','dim','18:00');
