-- ===== SEED Bobo partie 2 : B7, B7B, B8, B9, B10, B11, BAMA, NASSO =====
insert into departs (ligne, ville, terminus, jours, heure) values
-- ===== B7 : Station Amira Oil ↔ Tiéfo Amoro =====
('B7','Bobo-Dioulasso','Station Amira Oil','sem','05:45'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','07:05'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','08:25'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','10:20'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','12:05'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','13:30'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','14:50'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','16:10'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','17:30'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','18:50'),
('B7','Bobo-Dioulasso','Station Amira Oil','sem','20:15'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B7','Bobo-Dioulasso','Station Amira Oil','dim','07:00'),
('B7','Bobo-Dioulasso','Station Amira Oil','dim','09:00'),
('B7','Bobo-Dioulasso','Station Amira Oil','dim','11:00'),
('B7','Bobo-Dioulasso','Station Amira Oil','dim','13:00'),
('B7','Bobo-Dioulasso','Station Amira Oil','dim','15:00'),
('B7','Bobo-Dioulasso','Station Amira Oil','dim','17:00'),
('B7','Bobo-Dioulasso','Station Amira Oil','dim','19:00'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','dim','14:00'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','dim','16:00'),
('B7','Bobo-Dioulasso','Tiéfo Amoro','dim','18:00'),
-- ===== B7B : Santidougou ↔ Tiéfo Amoro =====
('B7B','Bobo-Dioulasso','Santidougou','sem','05:30'),
('B7B','Bobo-Dioulasso','Santidougou','sem','07:05'),
('B7B','Bobo-Dioulasso','Santidougou','sem','08:00'),
('B7B','Bobo-Dioulasso','Santidougou','sem','10:00'),
('B7B','Bobo-Dioulasso','Santidougou','sem','12:00'),
('B7B','Bobo-Dioulasso','Santidougou','sem','14:00'),
('B7B','Bobo-Dioulasso','Santidougou','sem','16:00'),
('B7B','Bobo-Dioulasso','Santidougou','sem','18:00'),
('B7B','Bobo-Dioulasso','Santidougou','sem','20:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','sem','07:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','sem','09:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','sem','13:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','sem','15:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','sem','17:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','sem','19:00'),
('B7B','Bobo-Dioulasso','Santidougou','dim','08:00'),
('B7B','Bobo-Dioulasso','Santidougou','dim','10:00'),
('B7B','Bobo-Dioulasso','Santidougou','dim','12:00'),
('B7B','Bobo-Dioulasso','Santidougou','dim','14:00'),
('B7B','Bobo-Dioulasso','Santidougou','dim','16:00'),
('B7B','Bobo-Dioulasso','Santidougou','dim','18:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','dim','07:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','dim','09:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','dim','11:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','dim','13:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','dim','15:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','dim','17:00'),
('B7B','Bobo-Dioulasso','Tiéfo Amoro','dim','19:00'),
-- ===== B8 : Dioulankolo ↔ Tiéfo Amoro =====
('B8','Bobo-Dioulasso','Dioulankolo','sem','05:45'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','07:05'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','08:25'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','10:20'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','12:05'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','13:30'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','14:50'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','16:10'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','17:30'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','18:50'),
('B8','Bobo-Dioulasso','Dioulankolo','sem','20:15'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B8','Bobo-Dioulasso','Dioulankolo','dim','07:00'),
('B8','Bobo-Dioulasso','Dioulankolo','dim','09:00'),
('B8','Bobo-Dioulasso','Dioulankolo','dim','11:00'),
('B8','Bobo-Dioulasso','Dioulankolo','dim','13:00'),
('B8','Bobo-Dioulasso','Dioulankolo','dim','15:00'),
('B8','Bobo-Dioulasso','Dioulankolo','dim','17:00'),
('B8','Bobo-Dioulasso','Dioulankolo','dim','19:00'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','dim','14:00'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','dim','16:00'),
('B8','Bobo-Dioulasso','Tiéfo Amoro','dim','18:00'),
-- ===== B9 : Marché du 22 ↔ Zone des écoles =====
('B9','Bobo-Dioulasso','Marché du 22','sem','05:30'),
('B9','Bobo-Dioulasso','Marché du 22','sem','06:50'),
('B9','Bobo-Dioulasso','Marché du 22','sem','08:10'),
('B9','Bobo-Dioulasso','Marché du 22','sem','09:25'),
('B9','Bobo-Dioulasso','Marché du 22','sem','10:45'),
('B9','Bobo-Dioulasso','Marché du 22','sem','12:05'),
('B9','Bobo-Dioulasso','Marché du 22','sem','13:05'),
('B9','Bobo-Dioulasso','Marché du 22','sem','14:25'),
('B9','Bobo-Dioulasso','Marché du 22','sem','15:45'),
('B9','Bobo-Dioulasso','Marché du 22','sem','17:05'),
('B9','Bobo-Dioulasso','Marché du 22','sem','18:25'),
('B9','Bobo-Dioulasso','Marché du 22','sem','19:45'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','06:10'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','07:30'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','08:50'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','10:05'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','11:25'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','12:45'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','13:45'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','15:05'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','16:25'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','17:45'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','19:05'),
('B9','Bobo-Dioulasso','Zone des écoles','sem','20:00'),
('B9','Bobo-Dioulasso','Marché du 22','dim','07:00'),
('B9','Bobo-Dioulasso','Marché du 22','dim','09:00'),
('B9','Bobo-Dioulasso','Marché du 22','dim','11:00'),
('B9','Bobo-Dioulasso','Marché du 22','dim','13:00'),
('B9','Bobo-Dioulasso','Marché du 22','dim','15:00'),
('B9','Bobo-Dioulasso','Marché du 22','dim','17:00'),
('B9','Bobo-Dioulasso','Marché du 22','dim','19:00'),
('B9','Bobo-Dioulasso','Zone des écoles','dim','08:00'),
('B9','Bobo-Dioulasso','Zone des écoles','dim','10:00'),
('B9','Bobo-Dioulasso','Zone des écoles','dim','12:00'),
('B9','Bobo-Dioulasso','Zone des écoles','dim','14:00'),
('B9','Bobo-Dioulasso','Zone des écoles','dim','16:00'),
('B9','Bobo-Dioulasso','Zone des écoles','dim','18:00'),
-- ===== B10 : IRA de Samagan ↔ Tiéfo Amoro =====
('B10','Bobo-Dioulasso','IRA de Samagan','sem','05:45'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','06:30'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','07:05'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','07:45'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','08:25'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','09:05'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','10:20'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','11:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','12:05'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','12:45'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','13:30'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','14:10'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','14:50'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','15:30'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','16:10'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','16:50'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','17:30'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','18:10'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','18:50'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','19:30'),
('B10','Bobo-Dioulasso','IRA de Samagan','sem','20:15'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','05:55'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','06:25'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','07:05'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','07:45'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','08:25'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','09:05'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','10:20'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','11:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','12:05'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','12:45'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','13:30'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','14:10'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','14:50'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','15:30'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','16:10'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','16:50'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','17:30'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','18:10'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','18:50'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','19:30'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','sem','20:15'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','07:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','08:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','09:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','10:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','11:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','12:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','13:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','14:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','15:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','16:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','17:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','18:00'),
('B10','Bobo-Dioulasso','IRA de Samagan','dim','19:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','07:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','08:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','09:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','11:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','12:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','13:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','14:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','15:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','16:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','17:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','18:00'),
('B10','Bobo-Dioulasso','Tiéfo Amoro','dim','19:00'),
-- ===== B11 : Belle Ville ↔ UCAO (nouvelle feuille 331/332) =====
('B11','Bobo-Dioulasso','Belle Ville','sem','05:30'),
('B11','Bobo-Dioulasso','Belle Ville','sem','07:00'),
('B11','Bobo-Dioulasso','Belle Ville','sem','08:40'),
('B11','Bobo-Dioulasso','Belle Ville','sem','10:20'),
('B11','Bobo-Dioulasso','Belle Ville','sem','12:00'),
('B11','Bobo-Dioulasso','Belle Ville','sem','13:40'),
('B11','Bobo-Dioulasso','Belle Ville','sem','15:10'),
('B11','Bobo-Dioulasso','Belle Ville','sem','16:50'),
('B11','Bobo-Dioulasso','Belle Ville','sem','19:25'),
('B11','Bobo-Dioulasso','UCAO','sem','06:10'),
('B11','Bobo-Dioulasso','UCAO','sem','07:50'),
('B11','Bobo-Dioulasso','UCAO','sem','09:30'),
('B11','Bobo-Dioulasso','UCAO','sem','11:10'),
('B11','Bobo-Dioulasso','UCAO','sem','12:50'),
('B11','Bobo-Dioulasso','UCAO','sem','14:30'),
('B11','Bobo-Dioulasso','UCAO','sem','16:00'),
('B11','Bobo-Dioulasso','UCAO','sem','17:40'),
('B11','Bobo-Dioulasso','UCAO','sem','20:05'),
('B11','Bobo-Dioulasso','Belle Ville','dim','07:00'),
('B11','Bobo-Dioulasso','Belle Ville','dim','09:00'),
('B11','Bobo-Dioulasso','Belle Ville','dim','11:00'),
('B11','Bobo-Dioulasso','Belle Ville','dim','13:00'),
('B11','Bobo-Dioulasso','Belle Ville','dim','13:15'),
('B11','Bobo-Dioulasso','Belle Ville','dim','15:15'),
('B11','Bobo-Dioulasso','Belle Ville','dim','17:15'),
('B11','Bobo-Dioulasso','UCAO','dim','08:15'),
('B11','Bobo-Dioulasso','UCAO','dim','10:15'),
('B11','Bobo-Dioulasso','UCAO','dim','12:15'),
('B11','Bobo-Dioulasso','UCAO','dim','14:15'),
('B11','Bobo-Dioulasso','UCAO','dim','16:15'),
('B11','Bobo-Dioulasso','UCAO','dim','18:15'),
-- ===== BBAMA : Bama ↔ Tiéfo Amoro (intercommunale) =====
('BBAMA','Bobo-Dioulasso','Bama','sem','05:30'),
('BBAMA','Bobo-Dioulasso','Bama','sem','07:00'),
('BBAMA','Bobo-Dioulasso','Bama','sem','08:30'),
('BBAMA','Bobo-Dioulasso','Bama','sem','10:00'),
('BBAMA','Bobo-Dioulasso','Bama','sem','11:30'),
('BBAMA','Bobo-Dioulasso','Bama','sem','13:00'),
('BBAMA','Bobo-Dioulasso','Bama','sem','16:00'),
('BBAMA','Bobo-Dioulasso','Bama','sem','19:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','sem','06:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','sem','07:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','sem','08:30'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','sem','10:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','sem','11:30'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','sem','14:30'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','sem','17:30'),
('BBAMA','Bobo-Dioulasso','Bama','dim','07:00'),
('BBAMA','Bobo-Dioulasso','Bama','dim','08:30'),
('BBAMA','Bobo-Dioulasso','Bama','dim','10:00'),
('BBAMA','Bobo-Dioulasso','Bama','dim','11:30'),
('BBAMA','Bobo-Dioulasso','Bama','dim','13:00'),
('BBAMA','Bobo-Dioulasso','Bama','dim','14:30'),
('BBAMA','Bobo-Dioulasso','Bama','dim','17:30'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','06:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','07:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','08:30'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','10:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','11:30'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','13:00'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','14:30'),
('BBAMA','Bobo-Dioulasso','Tiéfo Amoro','dim','17:30'),
-- ===== BNASSO : LSE 41 Nasso + 42 renfort (jours précisés) =====
('BNASSO','Bobo-Dioulasso','TOTAL RTE OUAGA','sem','06:00'),
('BNASSO','Bobo-Dioulasso','Tiéfo Amoro','sem','07:20'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','06:50'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','13:30'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','17:15'),
('BNASSO','Bobo-Dioulasso','Medersa Bindougousso','sem','07:00'),
('BNASSO','Bobo-Dioulasso','Medersa Bindougousso','sem','14:15'),
('BNASSO','Bobo-Dioulasso','Place de la Femme','sem','06:00'),
('BNASSO','Bobo-Dioulasso','Place de la Femme','sem','08:05'),
('BNASSO','Bobo-Dioulasso','Place de la Femme','sem','14:00'),
('BNASSO','Bobo-Dioulasso','Place de la Femme','sem','15:40'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','07:15'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','08:55'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','12:30'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','14:50'),
('BNASSO','Bobo-Dioulasso','Université Nazi Boni','sem','16:30');
